Show.create(:id => 1, :name => "Freeform", :dj => "Weston")
Show.create(:id => 2, :name => "Freeform", :dj => "Lizzy")
Show.create(:id => 3, :name => "Fififie fo Freeform", :dj => "DJ Fionn")
Show.create(:id => 4, :name => "Area of Refuge", :dj => "Sue")
Show.create(:id => 5, :name => "IHIH -or- Freeform", :dj => "Sam & Kat")
Show.create(:id => 6, :name => "Freeform", :dj => "Carrie R. -or- Greg H.")
Show.create(:id => 7, :name => "The Magic Number", :dj => "Paul...Stir")
Show.create(:id => 8, :name => "FSRN")
Show.create(:id => 13, :name => "The Daily Sports Report")
Show.create(:id => 17, :name => "Grey Matters")
Show.create(:id => 18, :name => "Yazoo City Calling", :dj => "Jerry Mack")
Show.create(:id => 19, :name => "Groovasaurus", :dj => "Mick")
Show.create(:id => 21, :name => "Freeform", :dj => "Nelson")
Show.create(:id => 22, :name => "Freeform", :dj => "Other Eli")
Show.create(:id => 23, :name => "Imagine That", :dj => "Christine")
Show.create(:id => 24, :name => "Jazz ''til Noon ''til Eleven")
Show.create(:id => 25, :name => "Radio Sputnik", :dj => "Comrade Rob")
Show.create(:id => 26, :name => "Exquisite Corpse", :dj => "Pascal")
Show.create(:id => 27, :name => "Bleached Meat", :dj => "Brandok")
Show.create(:id => 28, :name => "IT")
Show.create(:id => 29, :name => "Train to Skaville", :dj => "Brian Tomsic")
Show.create(:id => 30, :name => "Go Kat Go", :dj => "Del")
Show.create(:id => 33, :name => "Dim Your Lights", :dj => "D. Alfred")
Show.create(:id => 35, :name => "Ceci n''est pas Freeform", :dj => "Cameron")
Show.create(:id => 36, :name => "Transformations", :dj => "Pratt")
Show.create(:id => 37, :name => "Freeform", :dj => "Mary")
Show.create(:id => 38, :name => "Elysian Fields", :dj => "Orion")
Show.create(:id => 39, :name => "Living Writers", :dj => "T")
Show.create(:id => 40, :name => "Beat the Bezoar!", :dj => "Saramin")
Show.create(:id => 41, :name => "Local Music Show")
Show.create(:id => 42, :name => "Jammin'' with Jack Straw", :dj => "Jack")
Show.create(:id => 43, :name => "Freeform", :dj => "Ryan H.")
Show.create(:id => 44, :name => "Freeform", :dj => "Isaac")
Show.create(:id => 45, :name => "Short Stack", :dj => "Manos")
Show.create(:id => 46, :name => "Jazz Til Noon", :dj => "Michael Moo and KC")
Show.create(:id => 47, :name => "Freeform", :dj => "Winnie")
Show.create(:id => 48, :name => "Emergency Broadcast Hour", :dj => "David S.")
Show.create(:id => 49, :name => "Pandora's Lunchbox")
Show.create(:id => 50, :name => "Face the Music", :dj => "Arwulf")
Show.create(:id => 51, :name => "Sashay''s Shimmy Ko-Ko Bop Hour")
Show.create(:id => 52, :name => "The Object Lesson", :dj => "AA")
Show.create(:id => 54, :name => "The Equivalent", :dj => "Matt R.")
Show.create(:id => 55, :name => "Freeform", :dj => "Buddy")
Show.create(:id => 56, :name => "Dig", :dj => "Jason B.")
Show.create(:id => 57, :name => "Freeform", :dj => "Sean")
Show.create(:id => 58, :name => "Hugabug", :dj => "The Liz")
Show.create(:id => 59, :name => "Futfutfutfut Freestailo!", :dj => "Heidi")
Show.create(:id => 62, :name => "Tight Pants", :dj => "Kristin")
Show.create(:id => 63, :name => "Six O''Clock Shadow")
Show.create(:id => 64, :name => "Leisure Experiment")
Show.create(:id => 65, :name => "What It Is")
Show.create(:id => 67, :name => "Freeform", :dj => "Kyle or Elijah")
Show.create(:id => 68, :name => "The Answer is in the Beat", :dj => "Paul")
Show.create(:id => 69, :name => "Radio Debu", :dj => "Dave M.")
Show.create(:id => 70, :name => "Just Folkin'' Around")
Show.create(:id => 71, :name => "Bill Monroe")
Show.create(:id => 72, :name => "Down Home Show")
Show.create(:id => 73, :name => "Nothin'' But The Blues")
Show.create(:id => 74, :name => "Robot Pasta")
Show.create(:id => 75, :name => "Dancehall Reggae", :dj => "Brian Tomsic")
Show.create(:id => 78, :name => "Be Sure To Loop", :dj => "Non-James")
Show.create(:id => 79, :name => "Freeform", :dj => "Ren")
Show.create(:id => 80, :name => "Dead White Guys")
Show.create(:id => 81, :name => "Tsunami Dreams")
Show.create(:id => 82, :name => "Turkish Delight")
Show.create(:id => 83, :name => "Dromedary Express")
Show.create(:id => 84, :name => "Jaffa Jive")
Show.create(:id => 85, :name => "Latin Show")
Show.create(:id => 86, :name => "Radiozilla")
Show.create(:id => 87, :name => "Sounds of the Subcontinent")
Show.create(:id => 88, :name => "Prime Time for Harmolodics", :dj => "Tony")
Show.create(:id => 89, :name => "Horizons")
Show.create(:id => 90, :name => "Story Time")
Show.create(:id => 91, :name => "Pan African Heartbeat")
Show.create(:id => 60, :name => "Transmissions from Arrangar V", :dj => "Michael")
Show.create(:id => 61, :name => "Consensual Radio", :dj => "Brian")
Show.create(:id => 31, :name => "The Dream Machine", :dj => "Joy")
Show.create(:id => 53, :name => "Crush Collision")
Show.create(:id => 66, :name => "The Prescription", :dj => "St. James")
Show.create(:id => 76, :name => "Prop Shop", :dj => "Chill Will")
Show.create(:id => 92, :name => "KMFR Radio")
Show.create(:id => 34, :name => "Ones All Over The Place", :dj => "Brandon B.")
Show.create(:id => 77, :name => "ODIN''S DANCE PARTY")
Show.create(:id => 93, :name => "ALL FREEFORM")
Show.create(:id => 32, :name => "Freeform", :dj => "Norenbergh Du Soleil")
Show.create(:id => 94, :name => "Turn It Up", :dj => "Amy Wilson")
Show.create(:id => 20, :name => "Radio Rama Lama Fa Fa Fa -or- Booze, Broads, Boards and Rods", :dj => "Frank -or- Schmiddy")
